language: go
sudo: required

go:
  - 1.8

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - Project=apollo
    - pwd
    - mkdir $GOPATH/src/$Project
    - mv * $GOPATH/src/$Project
    - cd $GOPATH/src/$Project
    - pwd
    - ls -l

script:
    - go build -o "$Project"  "$Project"