language: go
sudo: required

go:
  - 1.8

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - Project=apollo
    - pwd 
    - mkdir $GOPATH/src/github.com/zouyx/$Project
    - mv * $GOPATH/src/github.com/zouyx/$Project
    - cd $GOPATH/src/github.com/zouyx/$Project

install:
    - go get github.com/cihub/seelog

script:
    - go build -o "$Project" github.com/zouyx/$Project
