language: go
sudo: required

go:
  - 1.8

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - Project=zouyx
    - mkdir $GOPATH/src/$Project
    - mv * $GOPATH/src/$Project
    - cd $GOPATH/src/$Project

script:
    - go build -o "$Project"  "$Project"