language: go
sudo: required

go:
  - 1.8

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - Project=apollo
    - mkdir $GOPATH/src/$Project
    - mv * $GOPATH/src/$Project
    - cd $GOPATH/src/$Project

install:
    - go get github.com/cihub/seelog

script:
    - go build -o "$Project"  github.com/zouyx/agollo
